version: "3.9"

services:

  weaviate:
    image: semitechnologies/weaviate:1.27.0
    ports:
      - "8080:8080"
      - "50051:50051"
    stop_grace_period: 5s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - REDIS_URL=redis://redis:6379
      - IMAGES_DIR=/app/images                          # ← ADD THIS
    depends_on:
      - weaviate
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./app:/app/app
      - huggingface_cache:/root/.cache/huggingface
      - ../fashion-dataset/images:/app/images           # ← ADD THIS

volumes:
  weaviate_data:
  huggingface_cache: